In [1]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
print(x)

tensor([[1.1753e+33, 4.5619e-41, 1.1753e+33],
        [4.5619e-41, 1.4602e-19, 1.8617e+25],
        [1.1835e+22, 4.3066e+21, 6.3828e+28],
        [1.4603e-19, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04]])


In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1457, 0.0765, 0.9100],
        [0.9939, 0.0369, 0.1061],
        [0.5794, 0.5459, 0.1701],
        [0.0348, 0.1003, 0.5046],
        [0.4353, 0.3527, 0.0493]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)      

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3015,  0.3145, -0.4952],
        [-1.7332,  1.1439, -0.6186],
        [ 0.1179,  0.2229,  0.2972],
        [ 0.0685, -0.2129, -1.3891],
        [ 0.7555,  0.6694, -0.1345]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9665,  0.3163, -0.3952],
        [-1.6759,  1.3083, -0.0981],
        [ 0.8518,  0.3417,  0.5528],
        [ 0.9459,  0.5476, -1.2022],
        [ 1.0914,  1.4449,  0.3234]])


In [9]:
print(torch.add(x, y))

tensor([[-0.9665,  0.3163, -0.3952],
        [-1.6759,  1.3083, -0.0981],
        [ 0.8518,  0.3417,  0.5528],
        [ 0.9459,  0.5476, -1.2022],
        [ 1.0914,  1.4449,  0.3234]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9665,  0.3163, -0.3952],
        [-1.6759,  1.3083, -0.0981],
        [ 0.8518,  0.3417,  0.5528],
        [ 0.9459,  0.5476, -1.2022],
        [ 1.0914,  1.4449,  0.3234]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.9665,  0.3163, -0.3952],
        [-1.6759,  1.3083, -0.0981],
        [ 0.8518,  0.3417,  0.5528],
        [ 0.9459,  0.5476, -1.2022],
        [ 1.0914,  1.4449,  0.3234]])


In [12]:
print(x[:, 1])

tensor([ 0.3145,  1.1439,  0.2229, -0.2129,  0.6694])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1237])
-1.123691439628601


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
#let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!